"""Inject SEO, Open Graph and favicon metadata into every page.

Before this, all 19 pages had exactly one useful head tag: <title>. No
description, so search engines wrote their own snippet from the first
paragraph. No Open Graph, so every link shared to LinkedIn, Slack or WhatsApp
rendered as a blank grey card. No favicon. No canonical, despite /Portfolio/
and /Portfolio/index.html serving identical content.

Also fixes two things while each head is open:
  - <html> gains lang="en"          (WCAG 3.1.1, and screen readers guess without it)
  - viewport drops user-scalable=no (WCAG 1.4.4, it blocked pinch zoom)

Idempotent: the block sits between sentinel comments and is replaced wholesale
on re-run. Titles are read from each file, never rewritten.
"""
import re
import sys
from pathlib import Path

ROOT = Path(sys.argv[1] if len(sys.argv) > 1 else ".")
BASE = "https://eandresge.github.io/Portfolio"

START = "<!-- meta:start (generated by tools/inject_meta.py) -->"
END = "<!-- meta:end -->"

# slug: (og:type, description, og:image:alt)
PAGES = {
    "index": ("website",
              "Geospatial Data Engineer building GIS automation with Python and FME. "
              "Portfolio of 15 professional, academic and personal spatial analysis projects.",
              "Andres Gordon, Geospatial Data Engineer, over a shaded relief map"),
    "work": ("website",
             "Professional experience: Geospatial Data Engineer at Sharper Shape, GIS "
             "Specialist at LUKE, and research assistant roles at the University of Eastern Finland.",
             "Professional experience of Andres Gordon"),
    "education": ("website",
                  "MSc in Biology of Environmental Change, Environmental Informatics, University "
                  "of Eastern Finland, and BSc Resource and Environmental Management, ANU.",
                  "Education of Andres Gordon"),
    "academic": ("website",
                 "Technical skills with evidence: FME, Dagster on Kubernetes, Python, AWS, "
                 "PostgreSQL, Mapbox vector tiling, ArcGIS Pro, QGIS, R, spatial modelling.",
                 "Technical skills of Andres Gordon"),

    "geoqc": ("article",
              "GeoQC Flow: a Python CLI that automates QA across multi-step FileGDB pipelines, "
              "classifying geometry changes by severity and generating HTML and DOCX reports.",
              "GeoQC Flow, automated pipeline QC and reporting"),
    "treeforge": ("article",
                  "TreeForge: a Python CLI that turns drone point clouds into a forest inventory, "
                  "producing DSM, DTM, canopy height model, tree crowns, treetops and a PDF report.",
                  "TreeForge, drone point cloud to forest inventory"),
    "powerornah": ("article",
                   "Power or Nah: an M5StickC IoT device that pulls Finnish ENTSO-E spot prices "
                   "and shows at a glance whether electricity is cheap right now.",
                   "Power or Nah, an IoT electricity price indicator device"),
    "pp1": ("article",
            "Paper-cut cartography of Quito: ArcGIS Pro DEM processing turned into a layered "
            "paper-cut map of the city's Andean topography at 2,850 m.",
            "Paper-cut cartographic map of Quito's topography"),

    "work1": ("article",
              "PPGIS mapping of conflict between social use areas and flying squirrel habitat "
              "across three Finnish municipalities, using Getis-Ord hotspots and R statistics.",
              "Public Participation GIS spatial conflict analysis"),
    "work2": ("article",
              "Moose-vehicle collision analysis with LUKE: regression modelling of 18 forest "
              "structure variables against collision density in Ostrobothnia and North Karelia.",
              "Moose-vehicle collision spatial analysis in Finland"),
    "work3": ("article",
              "Geospatial data engineering at Sharper Shape: Dagster on Kubernetes, FME, "
              "Python delivery pipelines to AWS S3, and Mapbox vector tiling.",
              "Geospatial data engineering at Sharper Shape"),
    "work4": ("article",
              "GIS database administration on LUKE's Rantalaidun project: digitising pasture "
              "areas, multi-criteria water sampling site selection, and geodatabase management.",
              "GIS database administration, Rantalaidun project"),

    "visibility": ("article",
                   "Viewshed analysis of proposed wind turbines at three sites near Joensuu, "
                   "Finland, mapping line-of-sight areas in ArcGIS Pro for impact assessment.",
                   "Wind turbine viewshed visibility analysis near Joensuu"),
    "risk": ("article",
             "Avalanche risk modelling in Valais, Switzerland: weighted overlay of slope, aspect, "
             "elevation, avalanche paths and population exposure to rank settlements.",
             "Avalanche risk model for the Valais canton, Switzerland"),
    "MCDA": ("article",
             "Multi-criteria site selection for a biathlon high school near Joensuu, balancing "
             "four competing spatial criteria in ArcGIS Pro Model Builder.",
             "Multi-criteria decision analysis site selection"),
    "geo": ("article",
            "Geostatistical interpolation of Finnish precipitation and European air pollutant "
            "data, comparing Kriging and IDW against a reference raster surface.",
            "Geostatistical interpolation surfaces"),
    "batch": ("article",
              "Batch processing Finnish Forest Centre open inventory data in Python and R, "
              "aggregating a 16x16 m grid to forest compartment level for management planning.",
              "Batch processing of open forest inventory data"),
    "network": ("article",
                "Network analysis of the proposed Stage 1 ACT light rail in Canberra: walking "
                "and driving service areas per stop, intersected with population data.",
                "Light rail accessibility network analysis, Canberra"),
    "remote": ("article",
               "Bushfire impact analysis in south-west Australia: NCI NetCDF data processed in "
               "MATLAB to compare tree cover, soil exposure and moisture before and after.",
               "Remote sensing analysis of bushfire impact in Australia"),
}


def esc(s):
    return s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;").replace('"', "&quot;")


def block(slug, title, og_type, desc, alt):
    url = f"{BASE}/" if slug == "index" else f"{BASE}/{slug}.html"
    img = f"{BASE}/images/og/{slug}.jpg"
    t, d, a = esc(title), esc(desc), esc(alt)
    return f"""{START}
		<meta name="description" content="{d}" />
		<meta name="author" content="Andres Gordon" />
		<link rel="canonical" href="{url}" />

		<meta property="og:type" content="{og_type}" />
		<meta property="og:site_name" content="Andres Gordon | GIS Portfolio" />
		<meta property="og:locale" content="en_GB" />
		<meta property="og:title" content="{t}" />
		<meta property="og:description" content="{d}" />
		<meta property="og:url" content="{url}" />
		<meta property="og:image" content="{img}" />
		<meta property="og:image:type" content="image/jpeg" />
		<meta property="og:image:width" content="1200" />
		<meta property="og:image:height" content="630" />
		<meta property="og:image:alt" content="{a}" />

		<meta name="twitter:card" content="summary_large_image" />
		<meta name="twitter:title" content="{t}" />
		<meta name="twitter:description" content="{d}" />
		<meta name="twitter:image" content="{img}" />
		<meta name="twitter:image:alt" content="{a}" />

		<link rel="icon" href="favicon.ico" sizes="any" />
		<link rel="icon" type="image/png" sizes="32x32" href="images/icons/favicon-32.png" />
		<link rel="icon" type="image/png" sizes="192x192" href="images/icons/favicon-192.png" />
		<link rel="apple-touch-icon" sizes="180x180" href="images/icons/apple-touch-icon.png" />
		<meta name="theme-color" content="#1b2030" />
{JSONLD if slug == "index" else ""}		{END}"""


# Structured data, index only. Every field is already stated on the site:
# job title and employer from work.html, degrees from education.html, skills
# from academic.html. Nothing here is invented.
JSONLD = """
		<script type="application/ld+json">
		{
		  "@context": "https://schema.org",
		  "@type": "Person",
		  "name": "Andres Gordon",
		  "jobTitle": "Geospatial Data Engineer",
		  "worksFor": { "@type": "Organization", "name": "Sharper Shape Group" },
		  "url": "%(BASE)s/",
		  "image": "%(BASE)s/images/og/index.jpg",
		  "sameAs": [
		    "https://github.com/EAndresGE",
		    "https://www.linkedin.com/in/andresgordon/"
		  ],
		  "alumniOf": [
		    { "@type": "CollegeOrUniversity", "name": "University of Eastern Finland" },
		    { "@type": "CollegeOrUniversity", "name": "Australian National University" }
		  ],
		  "knowsAbout": [
		    "Geographic Information Systems", "Spatial analysis", "FME",
		    "Python", "ArcGIS Pro", "QGIS", "Remote sensing", "LiDAR",
		    "Geospatial data engineering"
		  ]
		}
		</script>
""" % {"BASE": BASE}


def fix(path):
    slug = path.stem
    if slug not in PAGES:
        return None
    src = original = path.read_text(encoding="utf-8")
    notes = []

    m = re.search(r"<title>(.*?)</title>", src, re.S)
    if not m:
        return f"{path.name}: NO <title>, skipped"
    title = re.sub(r"\s+", " ", m.group(1)).strip()

    # 1. lang on <html>
    if not re.search(r"<html[^>]*\slang=", src, re.I):
        src = re.sub(r"<html(?![^>]*\slang=)([^>]*)>", r'<html lang="en"\1>', src, count=1, flags=re.I)
        notes.append("lang")

    # 2. viewport: drop user-scalable=no
    def vp(mm):
        c = re.sub(r"\s*,\s*user-scalable\s*=\s*no", "", mm.group(1), flags=re.I)
        return mm.group(0).replace(mm.group(1), c)

    new = re.sub(r'<meta\s+name="viewport"\s+content="([^"]*)"', vp, src, flags=re.I)
    if new != src:
        src = new
        notes.append("viewport")

    og_type, desc, alt = PAGES[slug]
    blk = block(slug, title, og_type, desc, alt)

    # 3. replace existing block, else insert after <meta charset>
    if START in src:
        src = re.sub(re.escape(START) + r".*?" + re.escape(END), blk, src, flags=re.S)
        notes.append("block:updated")
    else:
        cm = re.search(r'([ \t]*)<meta\s+charset="?[^">]*"?\s*/?>\s*\n', src, re.I)
        if not cm:
            return f"{path.name}: NO <meta charset>, skipped"
        indent = cm.group(1)
        src = src[:cm.end()] + indent + blk + "\n" + src[cm.end():]
        notes.append("block:added")

    if src != original:
        path.write_text(src, encoding="utf-8", newline="")
    return f"{path.name:22} {' '.join(notes)}"


if __name__ == "__main__":
    done = 0
    for f in sorted(ROOT.glob("*.html")):
        r = fix(f)
        if r:
            print("  " + r)
            done += 1
    print(f"\n{done} pages processed")
